name: Terraform Validate

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform_validate:
    name: "Validate Terraform Configuration"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check Terraform files
      run: |
        if ! grep -q 'backend "azurerm"' *.tf; then
          echo "Error: Azure backend configuration not found"
          exit 1
        fi
        if ! grep -q 'resource_group_name' *.tf || ! grep -q 'storage_account_name' *.tf || ! grep -q 'container_name' *.tf || ! grep -q 'key' *.tf; then
          echo "Error: Missing required backend configuration elements"
          exit 1
        fi
        echo "Terraform files check passed"

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
